name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm i -g --force corepack && corepack enable

      - name: Set node version to 20.19.5
        uses: actions/setup-node@v3
        with:
          node-version: '20.19.5'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run test cases
        run: pnpm test
